# Generated by Django 3.2.4 on 2021-06-17 15:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer',
            new_name='bestselling',
        ),
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='latest',
        ),
        migrations.AddField(
            model_name='product',
            name='banner_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='good'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_prod',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='upcoming',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
