# Generated by Django 3.2.4 on 2021-06-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_color_shopcart_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='size',
            new_name='color',
        ),
    ]
